const backdrop=document.getElementById('modal-backdrop');
const modal=document.getElementById('entry-modal');
function closeModal(){backdrop.classList.remove('open');backdrop.setAttribute('aria-hidden','true');modal.innerHTML='';}
function openLotForm(){
  modal.innerHTML=`<div class="modal-heading"><div><h2>Create gray inward lot</h2><p>Gray Inward / Received is set automatically. Saving creates the lot number and QR job-card record.</p></div><button class="modal-close" data-close-modal aria-label="Close">×</button></div><form class="modal-form" id="new-lot-form"><div class="form-row"><div class="field"><label>LR NUMBER</label><input class="input" name="lr" required placeholder="e.g. LR-42816/189"></div><div class="field"><label>FACTORY</label><select class="select" name="factory"><option>Factory S</option><option>Factory A</option></select></div></div><div class="field"><label>PARTY</label><select class="select" name="party">${seed.parties.map(p=>`<option>${p.name}</option>`).join('')}</select></div><div class="form-row"><div class="field"><label>QUALITY / FABRIC</label><input class="input" name="fabric" required placeholder="e.g. Cotton voile · 60s"></div><div class="field"><label>INPUT METERS</label><input class="input" name="qty" required type="number" min="1" placeholder="e.g. 1240"></div></div><div class="form-row"><div class="field"><label>LOT WEIGHT (KG)</label><input class="input" name="weightKg" required type="number" min="1" placeholder="e.g. 305"></div><div class="field"><label>PROCESS ROUTE</label><select class="select" name="route"><option>Cotton</option><option>Polyester</option><option>Rayon</option></select></div></div><div class="field"><label>INWARD NOTE (OPTIONAL)</label><input class="input" name="note" placeholder="e.g. colour chart attached / both side"></div><div class="callout green" style="margin:0">Initial stage: <strong>Gray Inward / Received</strong>. Process routing begins after this job card is issued.</div><div class="modal-footer">${btn('Cancel','ghost','close-modal')}<button class="btn primary" type="submit">Create lot & QR job card →</button></div></form>`;
  backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');setTimeout(()=>modal.querySelector('input')?.focus(),0);
  document.getElementById('new-lot-form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget);const max=Math.max(...state.lots.map(l=>Number(l.id.replace('LOT-',''))));const id=`LOT-${max+1}`;state.lots.unshift({id,party:data.get('party'),fabric:data.get('fabric'),qty:`${Number(data.get('qty')).toLocaleString('en-IN')} m`,weightKg:Number(data.get('weightKg')),lr:data.get('lr'),factory:data.get('factory'),route:data.get('route'),stage:'Received',status:'Gray inward',progress:5,color:'blue',updated:'Just now',operator:'Gray Supervisor'});state.selected=id;state.detailTab='job';state.view='detail';closeModal();render();toast(`${id} created · QR job card is ready to print`);};
}
function openPartyForm(){
  modal.innerHTML=`<div class="modal-heading"><div><h2>Add party</h2><p>Create the party record before assigning it to a new lot.</p></div><button class="modal-close" data-close-modal aria-label="Close">×</button></div><form class="modal-form" id="new-party-form"><div class="field"><label>PARTY NAME</label><input class="input" name="name" required placeholder="e.g. Nira Textiles"></div><div class="form-row"><div class="field"><label>CITY</label><input class="input" name="city" required placeholder="e.g. Surat"></div><div class="field"><label>PRIMARY CONTACT</label><input class="input" name="contact" required placeholder="e.g. Priya Shah"></div></div><div class="modal-footer">${btn('Cancel','ghost','close-modal')}<button class="btn primary" type="submit">Add party →</button></div></form>`;
  backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');setTimeout(()=>modal.querySelector('input')?.focus(),0);
  document.getElementById('new-party-form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget);seed.parties.unshift({name:data.get('name'),city:`${data.get('city')} · no active lots`,contact:data.get('contact'),volume:'—'});closeModal();render();toast(`${data.get('name')} added to parties`);};
}
document.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action==='new-lot'||action==='add-party'){event.preventDefault();event.stopImmediatePropagation();action==='new-lot'?openLotForm():openPartyForm();return;}if(event.target.closest('[data-close-modal]')||event.target===backdrop){event.preventDefault();closeModal();}} ,true);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&backdrop.classList.contains('open'))closeModal();});
/* Clean UI behaviour applied to the canonical root app. */
const cleanBaseScan=scan;
dashboard=function(){const priority=state.lots.find(lot=>lot.id==='LOT-24071')||state.lots[0];return header('Overview','Today','',btn('Open priority lot','primary','clean-priority'))+`<section class="clean-focus-card"><span class="clean-eyebrow">NEXT ACTION</span><h2>${priority.id} needs a decision</h2><button class="clean-row-action" data-action="clean-priority">Review ${priority.id} →</button></section><section class="clean-section"><div class="clean-section-head"><h2>Today at a glance</h2></div><div class="clean-summary"><button data-view="pipeline"><strong>3</strong><span>Need attention</span></button><button data-view="pipeline"><strong>8</strong><span>In production</span></button><button data-view="pipeline"><strong>12</strong><span>Active lots</span></button></div></section><section class="clean-section"><div class="clean-section-head"><h2>Recent movement</h2><button class="text-btn" data-view="pipeline">See pipeline →</button></div><div class="clean-lot-list">${state.lots.slice(0,3).map(lot=>`<button class="clean-lot-row" data-lot="${lot.id}"><span><strong>${lot.id}</strong><small>${lot.party} · ${lot.stage}</small></span>${tag(lot.status,lot.color)}<b>›</b></button>`).join('')}</div></section>`;};
scan=function(){if(state.role==='storekeeper')return cleanBaseScan();const workerBack=state.role==='worker'?'<button class="worker-back" data-worker-exit>← Profiles</button>':'';return workerBack+header('Floor entry','Record output','','')+`<section class="clean-entry"><div class="panel clean-scan-card"><span class="clean-step">STEP 1 OF 2</span><h2>Scan the job card</h2><button class="btn primary" data-action="simulate-scan">Scan job card</button></div><form class="panel entry-form" id="entry-form"><div class="clean-step">STEP 2 OF 2</div><h2 class="panel-title">Enter output</h2><input id="entry-lot" type="hidden" value=""><div id="scan-lot-status" class="callout amber">Scan a job card to continue.</div><div class="field" id="scan-entry-fields" style="opacity:.45"><label>OUTPUT METERS</label><input class="input" id="entry-meters" inputmode="decimal" type="number" disabled placeholder="Scan required"></div><div id="clean-entry-advanced" hidden><div class="field" id="scan-entry-type"><label>ENTRY TYPE</label><select class="select" id="entry-type" disabled><option value="complete">Stage complete</option><option value="partial">Partial completion</option><option value="rework">Rework / reprocess</option></select></div><div class="field" id="scan-note"><label>NOTE (OPTIONAL)</label><input class="input" disabled placeholder="Add a short note"></div></div><button type="button" class="clean-quiet-action" data-show-entry-options hidden>More options</button><button class="btn primary" id="entry-submit" type="submit" disabled>Save output</button></form></section>`;};
document.addEventListener('click',event=>{const priority=event.target.closest('[data-action="clean-priority"]');if(priority){event.preventDefault();state.selected='LOT-24071';state.view='detail';state.detailTab='qc';render();return;}const more=event.target.closest('[data-show-entry-options]');if(more){event.preventDefault();document.getElementById('clean-entry-advanced').hidden=false;more.hidden=true;}const scanTrigger=event.target.closest('[data-action="simulate-scan"]');if(scanTrigger&&state.role!=='storekeeper')setTimeout(()=>{const button=document.querySelector('[data-show-entry-options]');if(button)button.hidden=false;},0);},true);
const cleanBaseRender=render;render=function(){cleanBaseRender();document.querySelectorAll('.filter-row button,.toolbar-toggles').forEach(node=>node.classList.add('clean-secondary-control'));};render();
setTimeout(()=>{financialControl=function(){if(state.role!=='owner')return header('Restricted','Financial control','',btn('← Overview','ghost','dashboard'))+restrictedCost();const row=(stage,contractor,meters,rate,status,payable)=>`<tr><td>${stage}</td><td>${contractor}</td><td>${meters}</td><td>${rate}</td><td>${tag(status,status==='Payable'?'green':status==='Not payable'?'amber':'blue')}</td><td>${payable}</td></tr>`;return header('Owner view','Financial control','',btn('Export','ghost','export'))+`<section class="financial-summary"><div class="financial-summary-heading"><div><span class="financial-kicker">Benchmarks</span><h2>Key numbers</h2></div></div><div class="cost-grid"><article class="cost-cell revenue"><div class="cost-cell-top"><span class="cost-icon">↗</span><span>Factory revenue</span></div><strong>₹14 <em>/ m</em></strong></article><article class="cost-cell chemical"><div class="cost-cell-top"><span class="cost-icon">◈</span><span>Chemical baseline</span></div><strong>₹2.00 <em>/ m</em></strong></article><article class="cost-cell opportunity"><div class="cost-cell-top"><span class="cost-icon">↓</span><span>Target cost</span></div><strong>₹1.80 <em>/ m</em></strong></article><article class="cost-cell rework"><div class="cost-cell-top"><span class="cost-icon">✓</span><span>Rework payable</span></div><strong>₹0</strong></article></div></section><section class="panel"><div class="panel-header"><h2 class="panel-title">Lot economics</h2>${tag('Owner only','green')}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>Lot</th><th>Revenue</th><th>Chemicals</th><th>Labour</th><th>Result</th></tr></thead><tbody><tr data-lot="LOT-24081" class="clickable"><td><strong>LOT-24081</strong></td><td>₹14 / m</td><td>Tracked</td><td>Verified</td><td>${tag('In progress','blue')}</td></tr><tr data-lot="LOT-24071" class="clickable"><td><strong>LOT-24071</strong></td><td>₹14 / m</td><td>QC correction</td><td>Original only</td><td>${tag('Review','amber')}</td></tr></tbody></table></div></section><section class="panel" style="margin-top:16px"><div class="panel-header"><h2 class="panel-title">Stage payables</h2>${tag('Owner only','green')}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>Stage</th><th>Contractor</th><th>Meters</th><th>Rate / m</th><th>Status</th><th>Payable</th></tr></thead><tbody>${row('Pretreatment','Assigned contractor','1,226 m','Configure','Pending rate','—')}${row('Dyeing','Ramesh K.','1,178 m','₹0.25','Payable','₹294.50')}${row('Dyeing · rework','Ramesh K.','490 m','₹0.25','Not payable','₹0')}${row('Finishing','Assigned contractor','—','Configure','Pending rate','—')}</tbody></table></div></section>`;};costing=()=>financialControl();},30);
pipeline=function(){const lots=state.lots.filter(lot=>lotStages(lot).some(stage=>stage!=='Dispatched')),board=state.pipelineMode!=='list';return `<section class="clean-pipeline"><div class="clean-pipeline-top"><div class="clean-pipeline-label">ACTIVE LOTS BY STAGE</div><div class="clean-view-toggle"><button class="${board?'active':''}" data-kanban-mode="board">Board</button><button class="${!board?'active':''}" data-kanban-mode="list">List</button></div></div>${board?kanbanBoard(lots):`<div class="clean-pipeline-list">${table(lots)}</div>`}</section>`;};
