const backdrop=document.getElementById('modal-backdrop');
const modal=document.getElementById('entry-modal');
function closeModal(){backdrop.classList.remove('open');backdrop.setAttribute('aria-hidden','true');modal.innerHTML='';}
function openLotForm(){
  modal.innerHTML=`<div class="modal-heading"><div><h2>Create gray inward lot</h2><p>Gray Inward / Received is set automatically. Saving creates the lot number and QR job-card record.</p></div><button class="modal-close" data-close-modal aria-label="Close">×</button></div><form class="modal-form" id="new-lot-form"><div class="form-row"><div class="field"><label>LR NUMBER</label><input class="input" name="lr" required placeholder="e.g. LR-42816/189"></div><div class="field"><label>FACTORY</label><select class="select" name="factory"><option>Factory S</option><option>Factory A</option></select></div></div><div class="field"><label>PARTY</label><select class="select" name="party">${seed.parties.map(p=>`<option>${p.name}</option>`).join('')}</select></div><div class="form-row"><div class="field"><label>QUALITY / FABRIC</label><input class="input" name="fabric" required placeholder="e.g. Cotton voile · 60s"></div><div class="field"><label>INPUT METERS</label><input class="input" name="qty" required type="number" min="1" placeholder="e.g. 1240"></div></div><div class="form-row"><div class="field"><label>LOT WEIGHT (KG)</label><input class="input" name="weightKg" required type="number" min="1" placeholder="e.g. 305"></div><div class="field"><label>PROCESS ROUTE</label><select class="select" name="route"><option>Cotton</option><option>Polyester</option><option>Rayon</option></select></div></div><div class="field"><label>INWARD NOTE (OPTIONAL)</label><input class="input" name="note" placeholder="e.g. colour chart attached / both side"></div><div class="callout green" style="margin:0">Initial stage: <strong>Gray Inward / Received</strong>. Process routing begins after this job card is issued.</div><div class="modal-footer">${btn('Cancel','ghost','close-modal')}<button class="btn primary" type="submit">Create lot & QR job card →</button></div></form>`;
  backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');setTimeout(()=>modal.querySelector('input')?.focus(),0);
  document.getElementById('new-lot-form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget);const max=Math.max(...state.lots.map(l=>Number(l.id.replace('LOT-',''))));const id=`LOT-${max+1}`;state.lots.unshift({id,party:data.get('party'),fabric:data.get('fabric'),qty:`${Number(data.get('qty')).toLocaleString('en-IN')} m`,weightKg:Number(data.get('weightKg')),lr:data.get('lr'),factory:data.get('factory'),route:data.get('route'),stage:'Received',status:'Gray inward',progress:5,color:'blue',updated:'Just now',operator:'Gray Supervisor'});state.selected=id;state.detailTab='job';state.view='detail';closeModal();render();toast(`${id} created · QR job card is ready to print`);};
}
function openPartyForm(){
  modal.innerHTML=`<div class="modal-heading"><div><h2>Add party</h2><p>Create the party record before assigning it to a new lot.</p></div><button class="modal-close" data-close-modal aria-label="Close">×</button></div><form class="modal-form" id="new-party-form"><div class="field"><label>PARTY NAME</label><input class="input" name="name" required placeholder="e.g. Nira Textiles"></div><div class="form-row"><div class="field"><label>CITY</label><input class="input" name="city" required placeholder="e.g. Surat"></div><div class="field"><label>PRIMARY CONTACT</label><input class="input" name="contact" required placeholder="e.g. Priya Shah"></div></div><div class="modal-footer">${btn('Cancel','ghost','close-modal')}<button class="btn primary" type="submit">Add party →</button></div></form>`;
  backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');setTimeout(()=>modal.querySelector('input')?.focus(),0);
  document.getElementById('new-party-form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget);seed.parties.unshift({name:data.get('name'),city:`${data.get('city')} · no active lots`,contact:data.get('contact'),volume:'—'});closeModal();render();toast(`${data.get('name')} added to parties`);};
}
document.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action==='new-lot'||action==='add-party'){event.preventDefault();event.stopImmediatePropagation();action==='new-lot'?openLotForm():openPartyForm();return;}if(event.target.closest('[data-close-modal]')||event.target===backdrop){event.preventDefault();closeModal();}} ,true);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&backdrop.classList.contains('open'))closeModal();});
/* Clean UI Mode: task-first screens with optional detail hidden until needed. */
const cleanBaseScan=scan;
dashboard=function(){const priority=state.lots.find(lot=>lot.id==='LOT-24071')||state.lots[0];return header('Overview','Today','Start with the one thing that needs attention.',btn('Open priority lot','primary','clean-priority'))+`<section class="clean-focus-card"><span class="clean-eyebrow">NEXT ACTION</span><h2>${priority.id} needs a decision</h2><p>QC has flagged a rework. Review the lot before sending it to re-dyeing.</p><button class="clean-row-action" data-action="clean-priority">Review ${priority.id} →</button></section><section class="clean-section"><div class="clean-section-head"><div><h2>Today at a glance</h2><p>Only the numbers that need a decision.</p></div></div><div class="clean-summary"><button data-view="pipeline"><strong>3</strong><span>Need attention</span></button><button data-view="pipeline"><strong>8</strong><span>In production</span></button><button data-view="pipeline"><strong>12</strong><span>Active lots</span></button></div></section><section class="clean-section"><div class="clean-section-head"><div><h2>Recent movement</h2><p>Open a lot for the full job card.</p></div><button class="text-btn" data-view="pipeline">See pipeline →</button></div><div class="clean-lot-list">${state.lots.slice(0,3).map(lot=>`<button class="clean-lot-row" data-lot="${lot.id}"><span><strong>${lot.id}</strong><small>${lot.party} · ${lot.stage}</small></span>${tag(lot.status,lot.color)}<b>›</b></button>`).join('')}</div></section>`;};
scan=function(){if(state.role==='storekeeper')return cleanBaseScan();const workerBack=state.role==='worker'?'<button class="worker-back" data-worker-exit>← Profiles</button>':'';return workerBack+header('Floor entry','Record output','Scan the job card, enter the meters, then save.','')+`<section class="clean-entry"><div class="panel clean-scan-card"><span class="clean-step">STEP 1 OF 2</span><h2>Scan the job card</h2><p>Use the QR sticker attached to the physical card.</p><button class="btn primary" data-action="simulate-scan">Scan job card</button></div><form class="panel entry-form" id="entry-form"><div class="clean-step">STEP 2 OF 2</div><h2 class="panel-title">Enter output</h2><p class="panel-caption">This unlocks after a successful scan.</p><input id="entry-lot" type="hidden" value=""><div id="scan-lot-status" class="callout amber">Scan a job card to continue.</div><div class="field" id="scan-entry-fields" style="opacity:.45"><label>OUTPUT METERS</label><input class="input" id="entry-meters" inputmode="decimal" type="number" disabled placeholder="Scan required"></div><div id="clean-entry-advanced" hidden><div class="field" id="scan-entry-type"><label>ENTRY TYPE</label><select class="select" id="entry-type" disabled><option value="complete">Stage complete</option><option value="partial">Partial completion</option><option value="rework">Rework / reprocess</option></select></div><div class="field" id="scan-note"><label>NOTE (OPTIONAL)</label><input class="input" disabled placeholder="Add a short note"></div></div><button type="button" class="clean-quiet-action" data-show-entry-options hidden>More options</button><button class="btn primary" id="entry-submit" type="submit" disabled>Save output</button></form></section>`;};
document.addEventListener('click',event=>{const priority=event.target.closest('[data-action="clean-priority"]');if(priority){event.preventDefault();state.selected='LOT-24071';state.view='detail';state.detailTab='qc';render();return;}const more=event.target.closest('[data-show-entry-options]');if(more){event.preventDefault();document.getElementById('clean-entry-advanced').hidden=false;more.hidden=true;}const scanTrigger=event.target.closest('[data-action="simulate-scan"]');if(scanTrigger&&state.role!=='storekeeper')setTimeout(()=>{const button=document.querySelector('[data-show-entry-options]');if(button)button.hidden=false;},0);},true);
const cleanBaseRender=render;render=function(){cleanBaseRender();document.querySelectorAll('.filter-row button,.toolbar-toggles').forEach(node=>node.classList.add('clean-secondary-control'));};render();
