const backdrop=document.getElementById('modal-backdrop');
const modal=document.getElementById('entry-modal');
function closeModal(){backdrop.classList.remove('open');backdrop.setAttribute('aria-hidden','true');modal.innerHTML='';}
function openLotForm(){
  modal.innerHTML=`<div class="modal-heading"><div><h2>Create gray inward lot</h2><p>Gray Inward / Received is set automatically. Saving creates the lot number and QR job-card record.</p></div><button class="modal-close" data-close-modal aria-label="Close">×</button></div><form class="modal-form" id="new-lot-form"><div class="form-row"><div class="field"><label>LR NUMBER</label><input class="input" name="lr" required placeholder="e.g. LR-42816/189"></div><div class="field"><label>FACTORY</label><select class="select" name="factory"><option>Factory S</option><option>Factory A</option></select></div></div><div class="field"><label>PARTY</label><select class="select" name="party">${seed.parties.map(p=>`<option>${p.name}</option>`).join('')}</select></div><div class="form-row"><div class="field"><label>QUALITY / FABRIC</label><input class="input" name="fabric" required placeholder="e.g. Cotton voile · 60s"></div><div class="field"><label>INPUT METERS</label><input class="input" name="qty" required type="number" min="1" placeholder="e.g. 1240"></div></div><div class="form-row"><div class="field"><label>LOT WEIGHT (KG)</label><input class="input" name="weightKg" required type="number" min="1" placeholder="e.g. 305"></div><div class="field"><label>PROCESS ROUTE</label><select class="select" name="route"><option>Cotton</option><option>Polyester</option><option>Rayon</option></select></div></div><div class="field"><label>INWARD NOTE (OPTIONAL)</label><input class="input" name="note" placeholder="e.g. colour chart attached / both side"></div><div class="callout green" style="margin:0">Initial stage: <strong>Gray Inward / Received</strong>. Process routing begins after this job card is issued.</div><div class="modal-footer">${btn('Cancel','ghost','close-modal')}<button class="btn primary" type="submit">Create lot & QR job card →</button></div></form>`;
  backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');setTimeout(()=>modal.querySelector('input')?.focus(),0);
  document.getElementById('new-lot-form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget);const max=Math.max(...state.lots.map(l=>Number(l.id.replace('LOT-',''))));const id=`LOT-${max+1}`;state.lots.unshift({id,party:data.get('party'),fabric:data.get('fabric'),qty:`${Number(data.get('qty')).toLocaleString('en-IN')} m`,weightKg:Number(data.get('weightKg')),lr:data.get('lr'),factory:data.get('factory'),route:data.get('route'),stage:'Received',status:'Gray inward',progress:5,color:'blue',updated:'Just now',operator:'Gray Supervisor'});state.selected=id;state.detailTab='job';state.view='detail';closeModal();render();toast(`${id} created · QR job card is ready to print`);};
}
function openPartyForm(){
  modal.innerHTML=`<div class="modal-heading"><div><h2>Add party</h2><p>Create the party record before assigning it to a new lot.</p></div><button class="modal-close" data-close-modal aria-label="Close">×</button></div><form class="modal-form" id="new-party-form"><div class="field"><label>PARTY NAME</label><input class="input" name="name" required placeholder="e.g. Nira Textiles"></div><div class="form-row"><div class="field"><label>CITY</label><input class="input" name="city" required placeholder="e.g. Surat"></div><div class="field"><label>PRIMARY CONTACT</label><input class="input" name="contact" required placeholder="e.g. Priya Shah"></div></div><div class="modal-footer">${btn('Cancel','ghost','close-modal')}<button class="btn primary" type="submit">Add party →</button></div></form>`;
  backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');setTimeout(()=>modal.querySelector('input')?.focus(),0);
  document.getElementById('new-party-form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget);seed.parties.unshift({name:data.get('name'),city:`${data.get('city')} · no active lots`,contact:data.get('contact'),volume:'—'});closeModal();render();toast(`${data.get('name')} added to parties`);};
}
document.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action==='new-lot'||action==='add-party'){event.preventDefault();event.stopImmediatePropagation();action==='new-lot'?openLotForm():openPartyForm();return;}if(event.target.closest('[data-close-modal]')||event.target===backdrop){event.preventDefault();closeModal();}} ,true);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&backdrop.classList.contains('open'))closeModal();});
